### ISSUE TITLE
[BUG] ssh: known host issue on first run

### ISSUE THREAD

**Issue by ChrisB9** [phpsu/phpsu#53]
If you run phpsu the first time, the phpsu sync command will likely issue an error that the host is not in the known host list.

### Possible Solutions:

- check on every single sync execution, whether host is known
- add an initial command where everything is being set up
- automatically fixing this error once sync runs
- prompt a question to ask whether its okay to fix this
- adding a parameter to the .ssh-config to allow unknown hosts

### Helpful resources:

ssh-keyscan -t rsa {server-name} | ssh-keygen -lv -f -
ssh-keyscan -t rsa -H {server-name} >> ~/.ssh/known_hosts
echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

**Comment by Kanti** [comment]
Current workaround is to connect to the host via `phpsu ssh <hostname>` and accept the hostkey
