### ISSUE TITLE
Bug: rsync does not syncronize dot-files

### ISSUE THREAD

**Issue by Cyb10101** [phpsu/phpsu#66]
rsync -a source/* destination/

does not syncronize dot-files. Rather use this:
rsync -a source/ destination/

source source/ source/ * source/.*
Are all different. I would always prefer slash (source /)...

**Comment by ChrisB9** [comment]
I think this is a wrong behaviour! I dont want hidden files unless i need them (especially all vcs files and editor-files)

**Comment by Cyb10101** [comment]
Is not it better to explicitly exclude these?
->addExclude('/.git')

Example:
rsync -av --keep-dirlinks --delete --exclude='/.idea' --exclude='/.git' --exclude='/.env' server:folder_www/ ./www/
  
.gitkeep, .gitignore should not be excluded.

Maybe it would be cooler if you can explicitly specify what is syncronized.

**Comment by ChrisB9** [comment]
adding it to the excludes is not nessecary as rsync provides a "--cvs-exclude" flag

**Comment by ChrisB9** [comment]
closes #67
