### ISSUE TITLE
Feature: Add Filesystem and Database excludes as array

### ISSUE THREAD

**Issue by Cyb10101** [phpsu/phpsu#69]
The possibility to add excludes as an array.

```php
$config = new \PHPSu\Config\GlobalConfig();
$config->addFilesystem(...)
    ->addExcludes(['*.mp4', '*.mp3', '*.zip']);
$config->addAppInstance(...)
    ->addDatabase(...)
    ->addExcludes('table1', 'table2');
```

**Comment by Cyb10101** [comment]
First version: https://github.com/phpsu/phpsu/pull/70
Second maybe better version: https://github.com/phpsu/phpsu/pull/71

**Comment by Kanti** [comment]
I like #70 a lot more than #71. But the PR needs Tests so we can merge it.
